cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\meshes && (curl -O https://github.com/phnxdrgn536/FLSun-v400/tree/main/cura/flsun_v400.stl)

cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\definitions && (curl -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_STOCK.def.json)

cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\extruders && (curl -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_extruder/flsun_v400_extruder_0.def.json)

cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\intent && md PETG PLA

cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\intent\PETG && (curl -O https://github.com/phnxdrgn536/FLSun-v400/tree/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Draft_Print_Quick.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/tree/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Fast_Print_Accurate.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Fast_Visual.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_High_Visual.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Normal_Quality_Accurate.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Normal_Visual.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_VeryDraft_Print_Quick.inst.cfg)

cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\intent\PLA && (curl -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Draft_Print_Quick.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Fast_Print_Accurate.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Fast_Visual.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_High_Visual.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Normal_Quality_Accurate.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Normal_Visual.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_VeryDraft_Print_Quick.inst.cfg)

cd C:\users\%UserName%\OneDrive\Documents\GitHub\test\quality && md ABS PETG PLA

curl -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_quality/flsun_v400_global_Draft_Quality.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_quality/flsun_v400_global_Fast_Quality.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_quality/flsun_v400_global_High_Quality.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_quality/flsun_v400_global_Normal_Quality.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_quality/flsun_v400_global_Superdraft_Quality.inst.cfg -O https://github.com/phnxdrgn536/FLSun-v400/blob/main/cura/flsun_v400_quality/flsun_v400_global_Verydraft_Quality.inst.cfg)
